INSERT INTO BUILDING(ID, NAME) VALUES(1, '158');
INSERT INTO BUILDING(ID, NAME) VALUES(2, 'EF');

INSERT INTO ROOM(ID, NAME, FLOOR,BUILDING_ID) VALUES(1, 'F1', 1, 1);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(2, 'F2', 2, 1);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(3, 'S129', 1, 2);


INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (1, 8, 'ON', 1);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (2, 0, 'OFF', 2);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (3, 4, 'OFF', 3);